### ISSUE TITLE
SignPdf Class  Error ??

### ISSUE THREAD

**Issue by ImpossibleChicken** [mfarkan/E-Imza-iTextSharp-ESYA-Api#2]
try
            {
                var pdfContentWithSign = _pdfSigner.SignPDF(requestDTO, requestDTO.pdfContent);
                System.IO.File.WriteAllBytes(@"C:\pdf_withDigital_Sign.pdf", pdfContentWithSign);
            }
            catch (Exception ex)
            {
                throw new Exception("Dosyanın imzalanması sırasında bir hata oluştu.");
            }

Merhaba Sürekli Catch Fonksiyon düşüyor yardımcı olurmusun ??

**Comment by mfarkan** [comment]
Merhaba , projeyle ilgili olarak elimde herhangi test yapabileceğim e-imza usb yok , bunu daha detaylı inip debug etmeniz gerekebilir.
